import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

const agent = readFileSync(resolve('supabase/functions/task-agent/index.ts'), 'utf8')
const worker = readFileSync(resolve('api/browser-worker.ts'), 'utf8')
const roonWorker = readFileSync(resolve('supabase/functions/agent-watch-sweep/index.ts'), 'utf8')
const benchmarkHarness = readFileSync(resolve('benchmarks/david-applications/harness.ts'), 'utf8')
const browser = readFileSync(resolve('api/_public-browser.ts'), 'utf8')
const app = readFileSync(resolve('src/main.ts'), 'utf8')
const browserDocs = readFileSync(resolve('docs/browser-execution.md'), 'utf8')
const qualificationRunner = readFileSync(resolve('benchmarks/david-applications/production-qualification.mjs'), 'utf8')
const controller = readFileSync(resolve('supabase/functions/_shared/application-controller.ts'), 'utf8')
const engine = readFileSync(resolve('supabase/functions/_shared/application-engine.ts'), 'utf8')
const runtimePolicy = readFileSync(resolve('supabase/functions/_shared/application-runtime-policy.ts'), 'utf8')
const specialists = readFileSync(resolve('supabase/functions/_shared/specialists.ts'), 'utf8')

describe('production application completion contract', () => {
  it('sends private PNG and JPEG bytes to Luna multimodally', () => {
    expect(agent).toContain("type: 'input_image'")
    expect(agent).toContain("['image/png', 'image/jpeg']")
    expect(agent).toContain("model = 'gpt-5.6-luna'")
    expect(agent).not.toMatch(/model\s*:\s*['\"](?:sol|terra)/i)
  })

  it('generates private derived PDF assets with provenance and limits', () => {
    expect(agent).toContain("toolName === 'application.generate_document'")
    expect(agent).toContain('validateDocumentText')
    expect(agent).toContain("contentType: 'application/pdf'")
    expect(agent).toContain("source: 'roon_generated'")
    expect(agent).toContain('original_asset_id: originalAssetId')
  })

  it('offers an honest human-expert choice before drafting a graduate SOP', () => {
    expect(agent).toContain("code: 'sop_authoring_choice_required'")
    expect(agent).toContain('Bring in a human expert')
    expect(agent).toContain('Let Roon draft it')
    expect(agent).toContain('submission-ready for your approval')
    expect(agent).toContain('sop_authoring_choice')
    expect(agent).toContain('awaitingSopAuthoringChoice')
  })

  it('requires application evidence to be attached to the current task', () => {
    expect(agent).toContain("const isApplicationTask = /\\bapply\\b/i.test(title)")
    expect(agent).toContain("attachmentQuery.eq('task_id', taskId)")
    expect(agent).toContain(".eq('task_id', run.task_id)")
  })

  it('asks for the CV first when a screenshot has no attached applicant CV', () => {
    expect(agent).toContain("code: 'application_cv_required'")
    expect(agent).toContain('Please attach your current CV.')
    expect(agent).toContain("missing_fields: ['cv']")
    expect(agent).toContain('resum[eé]+')
  })

  it('materialises task-owned assets and verifies the browser file input', () => {
    expect(worker).toContain("from('file_assets')")
    expect(worker).toContain("from('private-file-assets').download")
    expect(browser).toContain('setInputFiles')
    expect(browser).toContain("kind: 'file_upload'")
    expect(browser).toContain('browser_upload_unverified')
    expect(browser).toContain("'--disable-gpu'")
    expect(browser).toContain('chromium.args.filter')
    expect(browser).toContain("'--single-process'")
    expect(browser).toContain('controlledProductionFixturePage')
    expect(browser).toContain('productionFixtureSyntheticCredential')
    expect(browser).toContain("/^Fixture-Run-[0-9]{4}!")
    expect(worker).toContain("[browser-worker] operation failed")
    expect(browser).toContain('required: Boolean(control.required)')
    expect(browser).toContain("browser_form_validation_required")
  })

  it('blocks ready-for-review without official-page, document, and upload evidence', () => {
    expect(agent).toContain('uploads.length < generated.length')
    expect(agent).toContain('navigations.length < 2')
    expect(agent).toContain('non_luna_reasoning_calls: 0')
  })

  it('keeps natural application wording observable and tolerates source-backed programme labels', () => {
    expect(agent).toContain('isApplicationIntent(current.objective')
    expect(agent).toContain('opportunityInput.programme')
    expect(agent).toContain('citationUrlFallback')
    expect(agent).toContain("sourceTypeValue === 'government'")
    expect(agent).toContain('opportunityInput.verified === true')
    expect(agent).toContain('current.context.attachments as Array<Record<string, unknown>>).length > 0')
    expect(agent).toContain('application_context_answers')
    expect(agent).toContain('AUTHORITATIVE_APPLICATION_CONTEXT_USER_ANSWERS_V1')
    expect(agent).toContain('safeString(run.context?.application_campaign_id, 80)')
    expect(agent).toContain('application_browser_recycled_action_id')
    expect(agent).toContain("['verified', ''].includes(requestedVerification)")
    expect(agent).toContain('run.browser_session_id')
    expect(agent).toContain('model typo as a cross-task ownership failure')
    expect(agent).toContain('application_browser_history_recovered')
    expect(agent).toContain("'browser_sensitive_field_blocked'")
    expect(qualificationRunner).toContain("'browser_session_missing'")
    expect(qualificationRunner).toContain("'portal_checkpoint_invalid'")
    expect(qualificationRunner).toContain('task-owned browser session')
    expect(agent).toContain('const wwwAlias = `www.${domain}`')
    expect(agent).toContain("'www.ed.ac.uk': 'study.ed.ac.uk'")
    expect(agent).toContain('repairedDomains')
    expect(agent).toContain('const shortlistApproved =')
    expect(agent).toContain('(shortlistApproved || internallyAuthorizedSingleProgramme || caseCreationRequested)')
    expect(agent).toContain("application_cases').select('id,opportunity_id,status')")
    expect(agent).toContain('targetCaseCount')
    expect(agent).toContain('campaignCaseIds.length < targetCaseCount')
    expect(agent).toContain("action: 'continue_application_controller'")
    expect(agent).toContain('current = await ensureCanonicalApplicationRuntime(admin, current)')
    expect(agent).toContain('const engineTools = applicationController ? toolsForApplicationEngineStep(applicationController) : null')
    expect(agent).toContain('if (isApplicationRun && !applicationController)')
    expect(agent).toContain('The canonical application controller snapshot is unavailable.')
    expect(agent).toContain("? { type: 'function', name: tools[0].name }")
    expect(agent).toContain(": 'required'")
    expect(agent).toContain("error_code: 'application_engine_tool_not_allowed'")
    expect(agent).toContain('normalizeApplicationEngineToolArguments(toolName, argumentsValue, applicationController)')
    expect(agent).toContain('normalized.requirement_id = snapshot.engineStep.requirementId')
    expect(agent).toContain('application_runtime_canonicalized')
    expect(agent).toContain('const failedApplicationRun = isApplicationIntent(run.objective')
    expect(agent).toContain('completion_continuations: 0')
    expect(agent).toContain('internal_failure_recovery_attempts: 0')
    expect(agent).toContain('David is resuming from the last verified application state.')
    expect(app).toContain("const dateTime = typeof deadline?.dateTime === 'string'")
    expect(app).toContain("if (!dateTime) return ''")
    expect(runtimePolicy).toContain("if (state === 'CASE_CREATION')")
    expect(runtimePolicy).toContain("return new Set(['agent.request_context'])")
    expect(runtimePolicy).not.toContain("'browser.submit',\n] as const")
    for (const tool of [
      'application.resolve_supplemental_questions',
      'application.generate_supervisor_outreach',
      'application.prepare_research_proposal',
      'application.coordinate_fee',
    ]) expect(specialists).toContain(`'${tool}'`)
    expect(agent).toContain('normalizeApplicationCreateCaseArguments')
    expect(agent).toContain("select('id,official_url,application_url')")
    expect(agent).toContain('input.label ?? input.title')
    expect(agent).toContain('input.source_urls ?? input.sourceUrls')
    expect(agent).toContain('ensureOfficialRequirementEvidence')
    expect(agent).toContain("kind: 'official_requirement_source'")
    expect(agent).toContain('canUseOfficialRequirementEvidence')
    expect(agent).toContain('application_invalid_official_evidence_removed')
    expect(agent).toContain('normalizePortalCheckpointInput')
    expect(agent).toContain('input.portal_url ?? input.portalUrl')
    expect(agent).toContain('input.provider_evidence ?? input.providerEvidence')
    expect(agent).toContain('input.enteredFacts ?? input.entered_facts')
    expect(agent).toContain('input.provider_confirmation ?? input.providerConfirmation')
    expect(agent).toContain('input.readAfterWriteVerified === true')
    expect(agent).toContain('completion_signal: completionSignal || null')
    expect(agent).toContain('verification_evidence_ids: evidenceIds')
    expect(agent).toContain('idempotency_key,created_at')
    expect(agent).toContain('application_portal_evidence_reconciled')
    expect(engine).toContain('verifiedRefereeFacts')
    expect(agent).toContain("if (/identity|contact details?|education|academic history|research history|employment history|applicant profile/.test(value)) return 'portal_section'")
    expect(agent).toContain("code: 'application_assignment_required'")
    expect(agent).toContain("code: 'application_requirement_awaiting_user'")
    expect(agent).toContain('actionSucceeded: true')
    expect(agent).toContain('const blockerReason = safeString(argumentsValue.blocker_reason')
    expect(agent).toContain('Boolean(effectiveBlockerReason && !terminalRequirementStatuses.includes(effectiveStatus))')
    expect(agent).toContain("select('id,application_case_id,name,verification_evidence_ids')")
    expect(agent).toContain('...stringArray(requirement.data.verification_evidence_ids, 120)')
    expect(agent).toContain("['in_progress', 'awaiting_institution', 'awaiting_user'].includes(status) && blockerReason && verificationEvidenceIds.length")
    expect(agent).toContain("safeString(item.kind, 120) === 'official_requirement_source'")
    expect(controller).toContain('evidenceIds, blocker }) => ({ id, name, status, dependencyIds, responsible, deadline, evidenceIds, blocker })')
    expect(agent).toContain('const applicationContextRecovery = run.status === \'waiting_for_user\'')
    expect(agent).toContain('applicationContextResumed = true')
    expect(agent).toContain("application_opportunities').select('id,institution,programme_title,official_url,application_url,verification_status,confidence,fit_score')")
    expect(agent).toContain('verifiedOpportunities')
    expect(agent).toContain('application_requirement_evidence_reconciled')
    expect(agent).toContain("['unknown', 'in_progress', 'awaiting_institution', 'awaiting_user'].includes(rawStatus)")
    expect(agent).toContain('safeString(message, 4_000).replace')
    expect(runtimePolicy).toContain("portal_section: ['browser.start_session', 'browser.navigate', 'browser.observe', 'browser.act', 'browser.submit'")
    expect(agent).toContain('submissionAttempted: null')
    expect(agent).toContain('agent_browser_validation_recovered')
    expect(agent).toContain('normalizeControlledFixtureNavigation')
    expect(agent).toContain('controlledFixtureContext')
    expect(agent).toContain('cannot silently fall back to an unscoped account page')
    expect(agent).toContain('stable_consequential_idempotency_key_before_approval')
    expect(agent).toContain('before creating another approval')
    expect(agent).toContain('agent_approval_replay_recovered')
    expect(agent).toContain('Reset a stale approval continuation')
    expect(agent).toContain('agent_model_rate_limit_retry_scheduled')
    expect(agent).toContain('model_rate_limit_count')
    expect(agent).toContain('model_rate_limit_count: 0')
    expect(agent).toContain('the lease is re-entrant')
    expect(browser).toContain('The submit response is a new resumable page')
    expect(browser).toContain('actions: [],')
  })

  it('keeps the synthetic David qualification hosts in the documented browser allowlist', () => {
    for (const host of ['www.imperial.ac.uk', 'study.ed.ac.uk', 'web.cs.toronto.edu', 'www.grad.ubc.ca', 'www.cs.ubc.ca']) {
      expect(browserDocs).toContain(host)
    }
  })

  it('queries only columns that exist when collecting production qualification evidence', () => {
    expect(qualificationRunner).toContain('application_evidence?select=id,application_case_id,kind,source_url,provider,provider_message_id,provider_thread_id,excerpt,captured_at')
    expect(qualificationRunner).toContain('application_communications?select=id,application_case_id,provider,direction,classification,provider_message_id,provider_thread_id,created_at')
    expect(qualificationRunner).not.toContain('application_evidence?select=id,application_case_id,kind,verified')
    expect(qualificationRunner).not.toContain('application_communications?select=id,application_case_id,provider,direction,status')
  })

  it('resumes bounded browser failures against the saved production run', () => {
    expect(qualificationRunner).toContain("'browser_worker_unavailable'")
    expect(qualificationRunner).toContain("'browser_retry_exhausted'")
    expect(qualificationRunner).toContain("action: 'resume', runId, context: ''")
    expect(qualificationRunner).toContain('explicit-application-requirements')
    expect(qualificationRunner).toContain('semantic-evidence-recovery')
    expect(qualificationRunner).toContain('human-assignment-recovery')
    expect(qualificationRunner).toContain('primary-referee-identity')
    expect(qualificationRunner).toContain("name: 'Dr. Amina Bello'")
    expect(qualificationRunner).toContain('select=id,consent_granted,updated_at,profile')
    expect(qualificationRunner).toContain("if (/shortlist|strategy approval|approve the (?:exact )?(?:three|selected)")
    expect(qualificationRunner).toContain('opportunity-id-recovery')
    expect(qualificationRunner).toContain('application_opportunities?campaign_id=eq.')
    expect(qualificationRunner).toContain('run?.applicationState?.campaignId')
    expect(qualificationRunner).toContain("run.status === 'waiting_for_user' || run.status === 'needs_approval'")
    expect(qualificationRunner).toContain('waiting_for_approval_record')
    expect(qualificationRunner).toContain('resuming_stale_approval_state')
    expect(qualificationRunner).toContain("does not|doesn't|not")
    expect(qualificationRunner).toContain('model_rate_limit_retry')
    expect(qualificationRunner).toContain('temporarily rate limited')
  })

  it('turns an authorised referee support pack into a review-only Gmail draft', () => {
    expect(roonWorker).toContain('applicationRefereeSupportPack')
    expect(roonWorker).toContain('applicationRefereeDraftPayload')
    expect(roonWorker).toContain('referee_email')
    expect(roonWorker).toContain('authorised referee in persisted application support pack')
    expect(roonWorker).toContain('body_text: safeString(input.body_text ?? input.body, 30_000) || bodyLines')
    expect(roonWorker).toContain("['create_draft', 'send_email'].includes(requestKind) ? applicationRefereeDraftPayload(context, rawPayload) : rawPayload")
    expect(roonWorker).toContain('function applicationContactKind')
    expect(roonWorker).toContain("if (!sendRequested) {")
  })

  it('preserves the pre-submit browser checkpoint across a retryable save failure', () => {
    expect(benchmarkHarness).toContain('const confirmedState = this.state')
    expect(benchmarkHarness).toContain('The portal\'s failure page is a new, non-resumable document')
    expect(benchmarkHarness).toContain('this.state = confirmedState')
    expect(benchmarkHarness).toContain('retryCheckpoint: this.state')
  })

  it('recovers a stalled application turn without changing the frozen email or flight polling paths', () => {
    expect(app).toContain('const staleApplicationRuns')
    expect(app).toContain("isApplicationIntent(run.objective, run.context)")
    expect(app).toContain("['planning', 'running'].includes(run.status)")
    expect(app).toContain('const stalePaymentHandoffRuns')
    expect(app).toContain("run.capability === 'flight_search'")
    expect(app).toContain('Boolean(run.result?.paymentHandoffUrl)')
    expect(app).toContain("run.status === 'waiting_external'")
  })
})
